print("please enter your school name")
name=input()
print("please enter your school email")
email=input()
print("please enter your school address")
address=input()
print("please enter your school phone number")
phone_number=input()
print("details" ,name ,email ,address ,phone_number)